swagger: '2.0'
info:
  version: 0.0.1
  title: Projekt Cool-Aid
  description: Office hours booking system. Legally distinct from the trademarked beverage.

paths:
  /user:
    post:
      summary: Add a new user.
      parameters: 
        - in: body
          name: body
          description: Student object.
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '405':
          description: Invalid input.
  /user/login:
    get:
      summary: Login user.
      parameters: 
        - name: utorId
          in: query
          description: The username.
          required: true
          type: string
        - name: studentNumber
          in: query
          description: The password.
          required: true
          type: string
      responses:
        '200':
          description: Successful login.
  /user/logout:
    get:
      summary: Logout user.
      responses:
        '200':
          description: Successful logout.
  
definitions:
  User:
    type: object
    properties:
      utorId:
        type: string
      studentNumber:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      instructor:
        type: boolean
        description: Whether user has instructor privileges.
  
  Class:
    type: string
    description: e.g. CSC302
  
  Meeting:
    type: object
    properties:
      instructor:
        type: string
        description: UtorId of the assigned instructor.
      class:
        $ref: '#/definitions/Class'
      comment:
        type: string
        description: Comment left by instructor.
      sessions:
        $ref: '#/definitions/Intervals'
  
  Intervals:
    type: array
    items:
      type: object
      properties:
        startTime:
          type: integer
          description: Unix time.
        duration:
          type: integer
          description: Seconds.
        student:
          type: string
          description: UtorId of the assigned student (can be empty).
        note:
          type: string
          description: Note left by student. Should be deleted on updating student.
      
