openapi: 3.0.0
info:
  title: Projekt Cool-Aid
  description: Office hours booking system. Legally distinct from the trademarked beverage.
  version: 0.0.1

paths:
  /user:
    post:
      summary: Add a new user.
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
      responses:
        '200':
          description: Successfully added user.
  /user/{utorId}:
    get:
      summary: Return a user.
      parameters:
      - name: utorId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully returned user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Edit a user.
      parameters:
      - name: utorId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
      responses:
        '200':
          description: Successfully edited user.
    delete:
      summary: Delete a user.
      parameters: 
      - name: utorId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully deleted user.
  
components:
  schemas:
    User:
      type: object
      properties:
        utorId:
          type: string
          example: rossbob2
        studentNumber:
          type: integer
          example: 1234567890
        firstName:
          type: string
          example: Bob
        lastName:
          type: string
          example: Ross
        role:
          type: string
          enum: [student, ta, instructor]
          example: instructor
        classes:
          type: array
          items:
            $ref: '#/components/schemas/Class'
    
    Class:
      type: string
      example: csc302
    
    Meeting:
      type: object
      properties:
        instructor:
          type: string
          description: UtorId of the assigned instructor.
          example: rossbob2
        class:
          $ref: '#/components/schemas/Class'
        comment:
          type: string
          description: Comment left by instructor.
          example: We don't make mistakes, just happy little accidents.
        startTime:
          type: integer
          description: Unix time.
        intervalDuration:
          type: integer
          description: Seconds per interval.
        intervals:
          description: A chronologically sorted dense array where startTime + index * intervalDuration = interval start time in unix time.
          type: array
          items:
            type: object
            properties:
              student:
                type: string
                description: UtorId of the assigned student (can be empty).
              note:
                type: string
                description: Note left by student. Should be deleted on updating student.
  
  requestBodies:
    UserBody:
      description: A JSON User object.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
